// <auto-generated />
namespace Sparrow_Delivery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addproductandcategorytables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproductandcategorytables));
        
        string IMigrationMetadata.Id
        {
            get { return "201806270940273_add product and category tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
